### ISSUE TITLE
Hi, can you provide the download link of phase#1 skeleton data, it seems not included in the provided BaiduYun.

### ISSUE THREAD

**Issue by Zhuysheng** [ECHO960/PKU-MMD#10]

**Comment by hitcbw** [comment]
I just found that in : [new project page]( http://39.96.165.147/Projects/PKUMMD/PKU-MMD.html)

**Comment by hitcbw** [comment]
I just found that in [new project page](http://39.96.165.147/Projects/PKUMMD/PKU-MMD.html)

**Comment by sankadivandya** [comment]
> I just found that in [new project page](http://39.96.165.147/Projects/PKUMMD/PKU-MMD.html)

Hi, This link doesn't contain the skeletons right? Besides I can't download these data since I'm from outside China and it seems we can't create a baidu account, which is needed apparently to download the data.

**Comment by ECHO960** [comment]
> > I just found that in [new project page](http://39.96.165.147/Projects/PKUMMD/PKU-MMD.html)
> 
> Hi, This link doesn't contain the skeletons right? Besides I can't download these data since I'm from outside China and it seems we can't create a baidu account, which is needed apparently to download the data.

you can find phase1-skeleton data from google drive: PKUMMD/data/skeleton.7z

**Comment by sankadivandya** [comment]
> > > I just found that in [new project page](http://39.96.165.147/Projects/PKUMMD/PKU-MMD.html)
> > 
> > 
> > Hi, This link doesn't contain the skeletons right? Besides I can't download these data since I'm from outside China and it seems we can't create a baidu account, which is needed apparently to download the data.
> 
> you can find phase1-skeleton data from google drive: PKUMMD/data/skeleton.7z

Hi,
Thanks for the reply. But PKUMMD google drive can't be accessed from my side.  I requested for access several times but it didn't work. If you can help with this that would be great. 
![image](https://user-images.githubusercontent.com/88878061/191138507-4de40651-de4e-449f-bb10-78cc027111f4.png)
![image](https://user-images.githubusercontent.com/88878061/191138281-76f9b952-1676-4efa-bc2b-ddc4632d47a3.png)
