### ISSUE TITLE
use new data to test

### ISSUE THREAD

**Issue by thekoshkina** [ECHO960/PKU-MMD#3]
How can I get a set of the joints in the same format? 
Some of the joint coordinates are negative. Can you please explain how these coordinates were calculated/ normalized?

**Comment by ECHO960** [comment]
these are raw joints captured by Microsoft Kinect v2. So there is no clue about how to map it to real world images, sorry. But you can try any  rigid transformation

**Comment by thekoshkina** [comment]
thank you
