### ISSUE TITLE
About names of action categories

### ISSUE THREAD

**Issue by SLime1998** [ECHO960/PKU-MMD#9]
Thanks for sharing your work, would you please provide us the action names?

**Comment by ECHO960** [comment]
v1: https://docs.google.com/spreadsheets/d/0B20a4UzO-OyMZzRXaFMzWjItY2M/edit?resourcekey=0-xEJfj_5ejzGiirKXrY8B9g#gid=858975855

v2: https://docs.google.com/spreadsheets/d/1begIo-QoN_qDOVoRIoF1tGAMDR_F9CLq/edit#gid=1123813840
